server:
  port: 8080

spring:
  application:
    name: microservices
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Invillia_db?useSSL=false
    username: root
    password: devLeandroInvillia!#
    